name: .NET Core Desktop

on:
  push:
    tags: "v*"
  pull_request:
    branches: [ master ]

jobs:

  build:
    permissions:
      contents: write

    strategy:
      matrix:
        configuration: [Release]
        rid: [win-x86, win-x64]
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: UltraWideScreenShare2.sln 
      Project_Path: UltraWideScreenShare.WinForms\UltraWideScreenShare.WinForms.csproj
      Project_Dir: UltraWideScreenShare.WinForms 

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}

    # Build app
    - name: Build the application
      run: dotnet publish $env:Project_Path -c $env:Configuration -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -p:DebugSymbols=false -r ${{ matrix.rid }}
      env:  
        Configuration: ${{ matrix.configuration }}

    # Upload files
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UltraWideScreenShare2-${{ matrix.rid }}
        path: ${{ env.Project_Dir }}\bin\${{ matrix.configuration }}\net9.0-windows10.0.22621.0\${{ matrix.rid }}\publish\
        compression-level: 1
  
    - name: Perform a Pester test from the command-line
      shell: pwsh
      run: Compress-Archive -Path ${{ env.Project_Dir }}\bin\${{ matrix.configuration }}\net9.0-windows10.0.22621.0\${{ matrix.rid }}\publish\* -Destination UltraWideScreenShare2-${{ matrix.rid }}.zip      

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: UltraWideScreenShare2-${{ matrix.rid }}.zip
